// cmd/build-installer.ts - build a release installer (and optionally the
// portable build) by hand, e.g. after local changes:
//
//   bun cmd/build-installer.ts            # SumatraPDF-3.7-64-install.exe
//   bun cmd/build-installer.ts --clean    # full rebuild of everything
//   bun cmd/build-installer.ts --tests    # run test_util unit tests first
//   bun cmd/build-installer.ts --portable # also make the static portable exe+zip
//   bun cmd/build-installer.ts --x86      # 32-bit installer
//
// What it does:
//  1. builds the SumatraPDF.exe installer executable (app code +
//     the embedded InstallerData.dat payload, regenerated by the prebuild step)
//  2. enforces the lightweight-moat EXE size guardrail (risk #1)
//  3. copies it to the canonical installer name
//     `out/<rel32|rel64>/SumatraPDF-<ver>-<32|64>-install.exe`
//  4. with --portable, also copies the static SumatraPDF.exe to
//     `SumatraPDF-<ver>-<32|64>.exe` and zips it.

import { copyFileSync } from "node:fs";
import { join } from "node:path";
import { detectVisualStudio, extractSumatraVersion, runLogged } from "./util";
import { enforceExeSizeLimit, kDefaultExeSizeLimitMb } from "./exe-size-limit";

type Arch = "x64" | "Win32";

interface Options {
  clean: boolean;
  runTests: boolean;
  portable: boolean;
  arch: Arch;
}

function usage(): never {
  console.log(`usage: bun cmd/build-installer.ts [options]

Builds the release installer (and optionally the portable build) from the
current source tree. Output goes to out/rel64 (or out/rel32 with --x86).

Options:
  --clean      full rebuild (msbuild Rebuild) instead of incremental build
  --tests      build & run test_util unit tests first (via run-unit-tests.ts)
  --portable   also build the static portable SumatraPDF-<ver>-<bits>.exe + .zip
  --x86        build the 32-bit installer instead of the 64-bit one
  --help       print this help and exit`);
  process.exit(1);
}

function parseArgs(): Options {
  const opts: Options = { clean: false, runTests: false, portable: false, arch: "x64" };
  for (const arg of process.argv.slice(2)) {
    switch (arg) {
      case "--clean":
        opts.clean = true;
        break;
      case "--tests":
        opts.runTests = true;
        break;
      case "--portable":
        opts.portable = true;
        break;
      case "--x86":
        opts.arch = "Win32";
        break;
      case "--help":
      case "-h":
        usage();
        break;
      default:
        console.log(`unknown option: ${arg}`);
        usage();
        break;
    }
  }
  return opts;
}

async function createPortableZip(exeName: string, outDir: string, zipName: string): Promise<void> {
  // use PowerShell to create the zip (same approach as build-ci.ts createPdbZip);
  // $ProgressPreference keeps Compress-Archive's progress bar out of the log
  const cmd = `$ProgressPreference='SilentlyContinue'; Compress-Archive -Path '${exeName}' -DestinationPath '${zipName}' -Force`;
  await runLogged("powershell", ["-Command", cmd], outDir);
}

async function main() {
  const opts = parseArgs();
  const timeStart = performance.now();

  const sumatraVer = extractSumatraVersion();
  const { msbuildPath } = detectVisualStudio();
  const config = "Release";
  const platform = opts.arch;
  const outDir = join("out", platform === "x64" ? "rel64" : "rel32");
  const bits = platform === "x64" ? "64" : "32";
  const sln = String.raw`vs2022\SumatraPDF.sln`;
  const p = `/p:Configuration=${config};Platform=${platform}`;

  console.log(`packaging SumatraPDF-${sumatraVer}-${bits}-install.exe (${config} ${platform})`);

  // optional: run the unit tests first so we don't package a broken build
  if (opts.runTests) {
    await runLogged("bun", [join("cmd", "run-unit-tests.ts"), "-rel"]);
  }

  // build the installer exe (SumatraPDF code + embedded InstallerData.dat,
  // which the prebuild step regenerates from the freshly built dlls)
  const tDll = `/t:SumatraPDF${opts.clean ? ":Rebuild" : ""}`;
  await runLogged(msbuildPath, [sln, tDll, p, `/m`]);

  // lightweight-moat guardrail: the release installer must stay small
  const dllExe = join(outDir, "SumatraPDF.exe");
  const r = enforceExeSizeLimit(dllExe, kDefaultExeSizeLimitMb);
  if (!r.ok) {
    throw new Error(`EXE size check failed: ${r.msg}`);
  }
  console.log(`EXE size check: ${r.sizeMb.toFixed(1)} MB <= ${r.limitMb} MB (${dllExe})`);

  // copy to the canonical installer name (IsInstallerOrUninstallerExe()
  // switches to installer mode based on the file name)
  const installName = `SumatraPDF-${sumatraVer}-${bits}-install.exe`;
  const installExe = join(outDir, installName);
  copyFileSync(dllExe, installExe);
  console.log(`created ${installExe}`);

  // optional: static portable build + zip
  if (opts.portable) {
    const tStatic = `/t:SumatraPDF-static${opts.clean ? ":Rebuild" : ""}`;
    await runLogged(msbuildPath, [sln, tStatic, p, `/m`]);
    // the static build embeds libmupdf etc., so it is bigger than the 15 MB
    // guardrail of the dll build; the size check intentionally doesn't apply.
    const portableName = `SumatraPDF-${sumatraVer}-${bits}.exe`;
    copyFileSync(join(outDir, "SumatraPDF-static.exe"), join(outDir, portableName));
    const zipName = `SumatraPDF-${sumatraVer}-${bits}.zip`;
    await createPortableZip(portableName, outDir, zipName);
    console.log(`created ${join(outDir, portableName)} and ${join(outDir, zipName)}`);
  }

  const elapsed = ((performance.now() - timeStart) / 1000).toFixed(1);
  console.log(`packaging took ${elapsed}s`);
}

await main();
